version: '3.6'

services:

  front:
    build: ./front
    ports:
      - "80:80"
    volumes:
      - ./images:/var/www/html/images
    depends_on:
      - storage

  storage:
    build: ./storage
    volumes:
      - ./images:/images

